parameters:
#    grass_intra.example.class: grass\IntraBundle\Example

services:
#    grass_intra.example:
#        class: %grass_intra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
